# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bibata-hyprcursor = {
    pname = "bibata-hyprcursor";
    version = "35ccfe209a808e40d6c2ca60a46cbe4faf68b690";
    src = fetchFromGitHub {
      owner = "ful1e5";
      repo = "Bibata_Cursor";
      rev = "35ccfe209a808e40d6c2ca60a46cbe4faf68b690";
      fetchSubmodules = false;
      sha256 = "sha256-kIKidw1vditpuxO1gVuZeUPdWBzkiksO/q2R/+DUdEc=";
    };
    date = "2024-06-18";
  };
  ikun-music-desktop = {
    pname = "ikun-music-desktop";
    version = "3.2.2";
    src = fetchurl {
      url = "https://github.com/ikunshare/ikun-music-desktop/releases/download/v3.2.2/ikun-music-desktop_3.2.2_x64.AppImage";
      sha256 = "sha256-Koqlq/LsA0/+rr3CKVI60I1NmIwNGS4gy27ahst1LRo=";
    };
  };
  librime-charcode = {
    pname = "librime-charcode";
    version = "55e7f563e999802d41a13ba02657c1be4b2011b4";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "librime-charcode";
      rev = "55e7f563e999802d41a13ba02657c1be4b2011b4";
      fetchSubmodules = false;
      sha256 = "sha256-KfKkpph+2ChQpkkGKubmpg/18uPX9qUHTqJT1PSGorI=";
    };
    date = "2024-03-19";
  };
  librime-lua = {
    pname = "librime-lua";
    version = "e3912a4b3ac2c202d89face3fef3d41eb1d7fcd6";
    src = fetchFromGitHub {
      owner = "hchunhui";
      repo = "librime-lua";
      rev = "e3912a4b3ac2c202d89face3fef3d41eb1d7fcd6";
      fetchSubmodules = false;
      sha256 = "sha256-zx0F41szn5qlc2MNjt1vizLIsIFQ67fp5cb8U8UUgtY=";
    };
    date = "2024-12-21";
  };
  librime-proto = {
    pname = "librime-proto";
    version = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-proto";
      rev = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
      fetchSubmodules = false;
      sha256 = "sha256-HdypebfmzreSdEQBwbvRG6sJZPASP+e8Tew+GrMnpOQ=";
    };
    date = "2023-10-17";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "51777daedbe4783c3b79f0246d775e4b6d978cbc";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "51777daedbe4783c3b79f0246d775e4b6d978cbc";
      fetchSubmodules = false;
      sha256 = "sha256-cFaFgChhpgEiJw+dHl3Hr3T2UQF+Vy6u36JWY+cYBNo=";
    };
    date = "2025-04-06";
  };
  vutron-music = {
    pname = "vutron-music";
    version = "1.7.5";
    src = fetchurl {
      url = "https://github.com/stark81/VutronMusic/releases/download/v1.7.5/VutronMusic-1.7.5_X86_64.AppImage";
      sha256 = "sha256-+jHQ60eYcZzHlgP4hHwkR8Ov5ZTK9T2uXyQl3IYAgwo=";
    };
  };
  wallpaper = {
    pname = "wallpaper";
    version = "f3f8175209a8d37331dd920b702d2b5c769997c5";
    src = fetchFromGitHub {
      owner = "indoordiary";
      repo = "PicList";
      rev = "f3f8175209a8d37331dd920b702d2b5c769997c5";
      fetchSubmodules = false;
      sha256 = "sha256-uXHIYitX5xnGGPusn/tqTudUea9pAFQex11e5zsfCuo=";
    };
    date = "2025-04-15";
  };
}
