# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-partuuid/5bfa71a1-cfde-46c8-bda4-86cefb9f4583";
      fsType = "btrfs";
      options = [
        "subvol=@"
        "compress=zstd"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-partuuid/5bfa71a1-cfde-46c8-bda4-86cefb9f4583";
      fsType = "btrfs";
      options = [
        "subvol=@home"
        "compress=zstd"
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-partuuid/5bfa71a1-cfde-46c8-bda4-86cefb9f4583";
      fsType = "btrfs";
      options = [ 
        "subvol=@nix"
        "noatime"
        "compress=zstd"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partuuid/369a342f-6343-44bd-bc34-80d89fcda436";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/dev/disk/by-partuuid/8f1d2eb8-2ed9-4ffa-8b69-d1280109aa2"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f4u1u4c2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
